//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4200.
// 
#pragma warning disable 1591

namespace ePortafolio.RubricOnService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RubricOnWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class RubricOnWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRutaEvaluarRubricaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRutaVerRubricaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRutaVerRubricaEvaluadaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RubricOnWebService() {
            this.Url = global::ePortafolio.Properties.Settings.Default.ePortafolio_RubricOnWebService_RubricOnWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRutaEvaluarRubricaCompletedEventHandler GetRutaEvaluarRubricaCompleted;
        
        /// <remarks/>
        public event GetRutaVerRubricaCompletedEventHandler GetRutaVerRubricaCompleted;
        
        /// <remarks/>
        public event GetRutaVerRubricaEvaluadaCompletedEventHandler GetRutaVerRubricaEvaluadaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRutaEvaluarRubrica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRutaEvaluarRubrica(EvaluarRubricaParam Param) {
            object[] results = this.Invoke("GetRutaEvaluarRubrica", new object[] {
                        Param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRutaEvaluarRubricaAsync(EvaluarRubricaParam Param) {
            this.GetRutaEvaluarRubricaAsync(Param, null);
        }
        
        /// <remarks/>
        public void GetRutaEvaluarRubricaAsync(EvaluarRubricaParam Param, object userState) {
            if ((this.GetRutaEvaluarRubricaOperationCompleted == null)) {
                this.GetRutaEvaluarRubricaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRutaEvaluarRubricaOperationCompleted);
            }
            this.InvokeAsync("GetRutaEvaluarRubrica", new object[] {
                        Param}, this.GetRutaEvaluarRubricaOperationCompleted, userState);
        }
        
        private void OnGetRutaEvaluarRubricaOperationCompleted(object arg) {
            if ((this.GetRutaEvaluarRubricaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRutaEvaluarRubricaCompleted(this, new GetRutaEvaluarRubricaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRutaVerRubrica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRutaVerRubrica(VerRubricaParam Param) {
            object[] results = this.Invoke("GetRutaVerRubrica", new object[] {
                        Param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRutaVerRubricaAsync(VerRubricaParam Param) {
            this.GetRutaVerRubricaAsync(Param, null);
        }
        
        /// <remarks/>
        public void GetRutaVerRubricaAsync(VerRubricaParam Param, object userState) {
            if ((this.GetRutaVerRubricaOperationCompleted == null)) {
                this.GetRutaVerRubricaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRutaVerRubricaOperationCompleted);
            }
            this.InvokeAsync("GetRutaVerRubrica", new object[] {
                        Param}, this.GetRutaVerRubricaOperationCompleted, userState);
        }
        
        private void OnGetRutaVerRubricaOperationCompleted(object arg) {
            if ((this.GetRutaVerRubricaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRutaVerRubricaCompleted(this, new GetRutaVerRubricaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRutaVerRubricaEvaluada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRutaVerRubricaEvaluada(VerRubricaEvaluadaParam Param) {
            object[] results = this.Invoke("GetRutaVerRubricaEvaluada", new object[] {
                        Param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRutaVerRubricaEvaluadaAsync(VerRubricaEvaluadaParam Param) {
            this.GetRutaVerRubricaEvaluadaAsync(Param, null);
        }
        
        /// <remarks/>
        public void GetRutaVerRubricaEvaluadaAsync(VerRubricaEvaluadaParam Param, object userState) {
            if ((this.GetRutaVerRubricaEvaluadaOperationCompleted == null)) {
                this.GetRutaVerRubricaEvaluadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRutaVerRubricaEvaluadaOperationCompleted);
            }
            this.InvokeAsync("GetRutaVerRubricaEvaluada", new object[] {
                        Param}, this.GetRutaVerRubricaEvaluadaOperationCompleted, userState);
        }
        
        private void OnGetRutaVerRubricaEvaluadaOperationCompleted(object arg) {
            if ((this.GetRutaVerRubricaEvaluadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRutaVerRubricaEvaluadaCompleted(this, new GetRutaVerRubricaEvaluadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EvaluarRubricaParam {
        
        private string rubricaIdField;
        
        private string tipoArtefactoField;
        
        private string codigoEvaluadoField;
        
        private string codigoEvaluadorField;
        
        private string parametroResultadoField;
        
        private string parametroCodigoEvaluacionField;
        
        private string rutaRetornoField;
        
        private string rutaCanceladoField;
        
        private System.Nullable<int> codigoEvaluacionPlantillaField;
        
        /// <remarks/>
        public string RubricaId {
            get {
                return this.rubricaIdField;
            }
            set {
                this.rubricaIdField = value;
            }
        }
        
        /// <remarks/>
        public string TipoArtefacto {
            get {
                return this.tipoArtefactoField;
            }
            set {
                this.tipoArtefactoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoEvaluado {
            get {
                return this.codigoEvaluadoField;
            }
            set {
                this.codigoEvaluadoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoEvaluador {
            get {
                return this.codigoEvaluadorField;
            }
            set {
                this.codigoEvaluadorField = value;
            }
        }
        
        /// <remarks/>
        public string ParametroResultado {
            get {
                return this.parametroResultadoField;
            }
            set {
                this.parametroResultadoField = value;
            }
        }
        
        /// <remarks/>
        public string ParametroCodigoEvaluacion {
            get {
                return this.parametroCodigoEvaluacionField;
            }
            set {
                this.parametroCodigoEvaluacionField = value;
            }
        }
        
        /// <remarks/>
        public string RutaRetorno {
            get {
                return this.rutaRetornoField;
            }
            set {
                this.rutaRetornoField = value;
            }
        }
        
        /// <remarks/>
        public string RutaCancelado {
            get {
                return this.rutaCanceladoField;
            }
            set {
                this.rutaCanceladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CodigoEvaluacionPlantilla {
            get {
                return this.codigoEvaluacionPlantillaField;
            }
            set {
                this.codigoEvaluacionPlantillaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VerRubricaEvaluadaParam {
        
        private int evaluacionIdField;
        
        private string rutaRetornoField;
        
        /// <remarks/>
        public int EvaluacionId {
            get {
                return this.evaluacionIdField;
            }
            set {
                this.evaluacionIdField = value;
            }
        }
        
        /// <remarks/>
        public string RutaRetorno {
            get {
                return this.rutaRetornoField;
            }
            set {
                this.rutaRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VerRubricaParam {
        
        private string rubricaIdField;
        
        private string tipoArtefactoField;
        
        private string rutaRetornoField;
        
        /// <remarks/>
        public string RubricaId {
            get {
                return this.rubricaIdField;
            }
            set {
                this.rubricaIdField = value;
            }
        }
        
        /// <remarks/>
        public string TipoArtefacto {
            get {
                return this.tipoArtefactoField;
            }
            set {
                this.tipoArtefactoField = value;
            }
        }
        
        /// <remarks/>
        public string RutaRetorno {
            get {
                return this.rutaRetornoField;
            }
            set {
                this.rutaRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetRutaEvaluarRubricaCompletedEventHandler(object sender, GetRutaEvaluarRubricaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRutaEvaluarRubricaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRutaEvaluarRubricaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetRutaVerRubricaCompletedEventHandler(object sender, GetRutaVerRubricaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRutaVerRubricaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRutaVerRubricaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetRutaVerRubricaEvaluadaCompletedEventHandler(object sender, GetRutaVerRubricaEvaluadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRutaVerRubricaEvaluadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRutaVerRubricaEvaluadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591