<?xml version="1.0" encoding="utf-8"?>
<Database Name="db_portafolio" Class="ePortafolioDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ZARATHOS-PC;Initial Catalog=db_portafolio;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db_portafolioConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Alumnos" Member="Alumnos">
    <Type Name="Alumno">
      <Column Name="AlumnoId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Alumno_AlumnosCurso" Member="AlumnosCursos" ThisKey="AlumnoId" OtherKey="AlumnoId" Type="AlumnosCurso" />
      <Association Name="Alumno_AlumnosGrupo" Member="AlumnosGrupos" ThisKey="AlumnoId" OtherKey="AlumnoId" Type="AlumnosGrupo" />
      <Association Name="Alumno_Archivo" Member="Archivos" ThisKey="AlumnoId" OtherKey="AlumnoId" Type="Archivo" />
    </Type>
  </Table>
  <Table Name="dbo.TrabajosResultadosPrograma" Member="TrabajosResultadosProgramas">
    <Type Name="TrabajosResultadosPrograma">
      <Column Name="TrabajoId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ResultadoProgramaId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ResultadosPrograma_TrabajosResultadosPrograma" Member="ResultadosPrograma" ThisKey="ResultadoProgramaId" OtherKey="ResultadoProgramaId" Type="ResultadosPrograma" IsForeignKey="true" />
      <Association Name="Trabajo_TrabajosResultadosPrograma" Member="Trabajo" ThisKey="TrabajoId" OtherKey="TrabajoId" Type="Trabajo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AlumnosCurso" Member="AlumnosCursos">
    <Type Name="AlumnosCurso">
      <Column Name="AlumnoId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CursoId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Alumno_AlumnosCurso" Member="Alumno" ThisKey="AlumnoId" OtherKey="AlumnoId" Type="Alumno" IsForeignKey="true" />
      <Association Name="Curso_AlumnosCurso" Member="Curso" ThisKey="CursoId" OtherKey="CursoId" Type="Curso" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AlumnosGrupo" Member="AlumnosGrupos">
    <Type Name="AlumnosGrupo">
      <Column Name="AlumnoId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GrupoId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EsLider" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Alumno_AlumnosGrupo" Member="Alumno" ThisKey="AlumnoId" OtherKey="AlumnoId" Type="Alumno" IsForeignKey="true" />
      <Association Name="Grupo_AlumnosGrupo" Member="Grupo" ThisKey="GrupoId" OtherKey="GrupoId" Type="Grupo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Archivos" Member="Archivos">
    <Type Name="Archivo">
      <Column Name="ArchivoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ruta" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TipoArchivoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AlumnoId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FechaSubida" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Extension" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Archivo_ArchivosGrupo" Member="ArchivosGrupos" ThisKey="ArchivoId" OtherKey="ArchivoId" Type="ArchivosGrupo" />
      <Association Name="Alumno_Archivo" Member="Alumno" ThisKey="AlumnoId" OtherKey="AlumnoId" Type="Alumno" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArchivosGrupo" Member="ArchivosGrupos">
    <Type Name="ArchivosGrupo">
      <Column Name="ArchivoId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GrupoId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Archivo_ArchivosGrupo" Member="Archivo" ThisKey="ArchivoId" OtherKey="ArchivoId" Type="Archivo" IsForeignKey="true" />
      <Association Name="Grupo_ArchivosGrupo" Member="Grupo" ThisKey="GrupoId" OtherKey="GrupoId" Type="Grupo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cursos" Member="Cursos">
    <Type Name="Curso">
      <Column Name="CursoId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProfesorId" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Curso_AlumnosCurso" Member="AlumnosCursos" ThisKey="CursoId" OtherKey="CursoId" Type="AlumnosCurso" />
      <Association Name="Curso_Trabajo" Member="Trabajos" ThisKey="CursoId" OtherKey="CursoId" Type="Trabajo" />
      <Association Name="Profesore_Curso" Member="Profesore" ThisKey="ProfesorId" OtherKey="ProfesorId" Type="Profesore" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Grupos" Member="Grupos">
    <Type Name="Grupo">
      <Column Name="GrupoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TrabajoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Grupo_AlumnosGrupo" Member="AlumnosGrupos" ThisKey="GrupoId" OtherKey="GrupoId" Type="AlumnosGrupo" />
      <Association Name="Grupo_ArchivosGrupo" Member="ArchivosGrupos" ThisKey="GrupoId" OtherKey="GrupoId" Type="ArchivosGrupo" />
      <Association Name="Grupo_ReultadosRubricaGrupo" Member="ReultadosRubricaGrupos" ThisKey="GrupoId" OtherKey="GrupoId" Type="ReultadosRubricaGrupo" />
      <Association Name="Trabajo_Grupo" Member="Trabajo" ThisKey="TrabajoId" OtherKey="TrabajoId" Type="Trabajo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Profesores" Member="Profesores">
    <Type Name="Profesore">
      <Column Name="ProfesorId" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Profesore_Curso" Member="Cursos" ThisKey="ProfesorId" OtherKey="ProfesorId" Type="Curso" />
    </Type>
  </Table>
  <Table Name="dbo.ResultadosPrograma" Member="ResultadosProgramas">
    <Type Name="ResultadosPrograma">
      <Column Name="ResultadoProgramaId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="ResultadosPrograma_TrabajosResultadosPrograma" Member="TrabajosResultadosProgramas" ThisKey="ResultadoProgramaId" OtherKey="ResultadoProgramaId" Type="TrabajosResultadosPrograma" />
    </Type>
  </Table>
  <Table Name="dbo.ReultadosRubricaGrupo" Member="ReultadosRubricaGrupos">
    <Type Name="ReultadosRubricaGrupo">
      <Column Name="RubricaId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GrupoId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Resultado" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Grupo_ReultadosRubricaGrupo" Member="Grupo" ThisKey="GrupoId" OtherKey="GrupoId" Type="Grupo" IsForeignKey="true" />
      <Association Name="Rubrica_ReultadosRubricaGrupo" Member="Rubrica" ThisKey="RubricaId" OtherKey="RubricaId" Type="Rubrica" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rubricas" Member="Rubricas">
    <Type Name="Rubrica">
      <Column Name="RubricaId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Rubrica_ReultadosRubricaGrupo" Member="ReultadosRubricaGrupos" ThisKey="RubricaId" OtherKey="RubricaId" Type="ReultadosRubricaGrupo" />
      <Association Name="Rubrica_RubricasTrabajo" Member="RubricasTrabajos" ThisKey="RubricaId" OtherKey="RubricaId" Type="RubricasTrabajo" />
    </Type>
  </Table>
  <Table Name="dbo.RubricasTrabajo" Member="RubricasTrabajos">
    <Type Name="RubricasTrabajo">
      <Column Name="RubricaId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TrabajoId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ponderacion" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Rubrica_RubricasTrabajo" Member="Rubrica" ThisKey="RubricaId" OtherKey="RubricaId" Type="Rubrica" IsForeignKey="true" />
      <Association Name="Trabajo_RubricasTrabajo" Member="Trabajo" ThisKey="TrabajoId" OtherKey="TrabajoId" Type="Trabajo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trabajos" Member="Trabajos">
    <Type Name="Trabajo">
      <Column Name="TrabajoId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CursoId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EsGrupal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaInicio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaFin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Iniciativa" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Instrucciones" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Trabajo_TrabajosResultadosPrograma" Member="TrabajosResultadosProgramas" ThisKey="TrabajoId" OtherKey="TrabajoId" Type="TrabajosResultadosPrograma" />
      <Association Name="Trabajo_Grupo" Member="Grupos" ThisKey="TrabajoId" OtherKey="TrabajoId" Type="Grupo" />
      <Association Name="Trabajo_RubricasTrabajo" Member="RubricasTrabajos" ThisKey="TrabajoId" OtherKey="TrabajoId" Type="RubricasTrabajo" />
      <Association Name="Curso_Trabajo" Member="Curso" ThisKey="CursoId" OtherKey="CursoId" Type="Curso" IsForeignKey="true" />
    </Type>
  </Table>
</Database>