#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortafolioMVC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="pyr_integrado")]
	public partial class pyrIntegradoDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public pyrIntegradoDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["pyr_integradoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public pyrIntegradoDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pyrIntegradoDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pyrIntegradoDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pyrIntegradoDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ePSE_Alumno> ePSE_Alumnos
		{
			get
			{
				return this.GetTable<ePSE_Alumno>();
			}
		}
		
		public System.Data.Linq.Table<ePSE_SeccionesCurso> ePSE_SeccionesCursos
		{
			get
			{
				return this.GetTable<ePSE_SeccionesCurso>();
			}
		}
		
		public System.Data.Linq.Table<ePSE_AlumnosCurso> ePSE_AlumnosCursos
		{
			get
			{
				return this.GetTable<ePSE_AlumnosCurso>();
			}
		}
		
		public System.Data.Linq.Table<ePSE_Curso> ePSE_Cursos
		{
			get
			{
				return this.GetTable<ePSE_Curso>();
			}
		}
		
		public System.Data.Linq.Table<ePSE_Periodo> ePSE_Periodos
		{
			get
			{
				return this.GetTable<ePSE_Periodo>();
			}
		}
		
		public System.Data.Linq.Table<ePSE_Profesore> ePSE_Profesores
		{
			get
			{
				return this.GetTable<ePSE_Profesore>();
			}
		}
		
		public System.Data.Linq.Table<ePSE_CursosPeriodo> ePSE_CursosPeriodos
		{
			get
			{
				return this.GetTable<ePSE_CursosPeriodo>();
			}
		}
	}
	
	[Table(Name="dbo.ePSE_Alumnos")]
	public partial class ePSE_Alumno
	{
		
		private string _AlumnoId;
		
		private string _Nombre;
		
		private string _CorreoElectronico;
		
		public ePSE_Alumno()
		{
		}
		
		[Column(Storage="_AlumnoId", DbType="VarChar(20)")]
		public string AlumnoId
		{
			get
			{
				return this._AlumnoId;
			}
			set
			{
				if ((this._AlumnoId != value))
				{
					this._AlumnoId = value;
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(153)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[Column(Storage="_CorreoElectronico", DbType="VarChar(31)")]
		public string CorreoElectronico
		{
			get
			{
				return this._CorreoElectronico;
			}
			set
			{
				if ((this._CorreoElectronico != value))
				{
					this._CorreoElectronico = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.ePSE_SeccionesCurso")]
	public partial class ePSE_SeccionesCurso
	{
		
		private string _PeriodoId;
		
		private int _CursoId;
		
		private string _SeccionId;
		
		private string _ProfesorId;
		
		private string _Nombre;
		
		public ePSE_SeccionesCurso()
		{
		}
		
		[Column(Storage="_PeriodoId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
		
		[Column(Storage="_CursoId", DbType="Int NOT NULL")]
		public int CursoId
		{
			get
			{
				return this._CursoId;
			}
			set
			{
				if ((this._CursoId != value))
				{
					this._CursoId = value;
				}
			}
		}
		
		[Column(Storage="_SeccionId", DbType="VarChar(4)")]
		public string SeccionId
		{
			get
			{
				return this._SeccionId;
			}
			set
			{
				if ((this._SeccionId != value))
				{
					this._SeccionId = value;
				}
			}
		}
		
		[Column(Storage="_ProfesorId", DbType="VarChar(20)")]
		public string ProfesorId
		{
			get
			{
				return this._ProfesorId;
			}
			set
			{
				if ((this._ProfesorId != value))
				{
					this._ProfesorId = value;
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(4)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.ePSE_AlumnosCurso")]
	public partial class ePSE_AlumnosCurso
	{
		
		private string _PeriodoId;
		
		private int _CursoId;
		
		private string _SeccionId;
		
		private string _AlumnoId;
		
		public ePSE_AlumnosCurso()
		{
		}
		
		[Column(Storage="_PeriodoId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
		
		[Column(Storage="_CursoId", DbType="Int NOT NULL")]
		public int CursoId
		{
			get
			{
				return this._CursoId;
			}
			set
			{
				if ((this._CursoId != value))
				{
					this._CursoId = value;
				}
			}
		}
		
		[Column(Storage="_SeccionId", DbType="Char(4)")]
		public string SeccionId
		{
			get
			{
				return this._SeccionId;
			}
			set
			{
				if ((this._SeccionId != value))
				{
					this._SeccionId = value;
				}
			}
		}
		
		[Column(Storage="_AlumnoId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string AlumnoId
		{
			get
			{
				return this._AlumnoId;
			}
			set
			{
				if ((this._AlumnoId != value))
				{
					this._AlumnoId = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.ePSE_Cursos")]
	public partial class ePSE_Curso
	{
		
		private int _CursoId;
		
		private string _Codigo;
		
		private string _Nombre;
		
		public ePSE_Curso()
		{
		}
		
		[Column(Storage="_CursoId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int CursoId
		{
			get
			{
				return this._CursoId;
			}
			set
			{
				if ((this._CursoId != value))
				{
					this._CursoId = value;
				}
			}
		}
		
		[Column(Storage="_Codigo", DbType="VarChar(10)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.ePSE_Periodos")]
	public partial class ePSE_Periodo
	{
		
		private string _PeriodoId;
		
		private bool _EsActual;
		
		public ePSE_Periodo()
		{
		}
		
		[Column(Storage="_PeriodoId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
		
		[Column(Storage="_EsActual", DbType="Bit NOT NULL")]
		public bool EsActual
		{
			get
			{
				return this._EsActual;
			}
			set
			{
				if ((this._EsActual != value))
				{
					this._EsActual = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.ePSE_Profesores")]
	public partial class ePSE_Profesore
	{
		
		private string _ProfesorId;
		
		private string _Nombre;
		
		public ePSE_Profesore()
		{
		}
		
		[Column(Storage="_ProfesorId", DbType="VarChar(20)")]
		public string ProfesorId
		{
			get
			{
				return this._ProfesorId;
			}
			set
			{
				if ((this._ProfesorId != value))
				{
					this._ProfesorId = value;
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(153)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.ePSE_CursosPeriodo")]
	public partial class ePSE_CursosPeriodo
	{
		
		private string _PeriodoId;
		
		private int _CursoId;
		
		private string _CoordinadorId;
		
		public ePSE_CursosPeriodo()
		{
		}
		
		[Column(Storage="_PeriodoId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
		
		[Column(Storage="_CursoId", DbType="Int NOT NULL")]
		public int CursoId
		{
			get
			{
				return this._CursoId;
			}
			set
			{
				if ((this._CursoId != value))
				{
					this._CursoId = value;
				}
			}
		}
		
		[Column(Storage="_CoordinadorId", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string CoordinadorId
		{
			get
			{
				return this._CoordinadorId;
			}
			set
			{
				if ((this._CoordinadorId != value))
				{
					this._CoordinadorId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
