<?xml version="1.0" encoding="utf-8"?>
<Database Name="SSIA" Class="SSIADBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=SSIA;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SSIAConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.LogrosCurso" Method="LogrosCurso">
    <Parameter Name="CursoId" Parameter="cursoId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PeriodoId" Parameter="periodoId" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="LogrosCursoResult">
      <Column Name="LogroId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Codigo" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>