//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortafolioMVC.IISA_WSP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IISA_WSP.IWSGeneral")]
    public interface IWSGeneral {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSGeneral/GetNombreAlumno", ReplyAction="http://tempuri.org/IWSGeneral/GetNombreAlumnoResponse")]
        string GetNombreAlumno(string Codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWSGeneralChannel : ePortafolioMVC.IISA_WSP.IWSGeneral, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WSGeneralClient : System.ServiceModel.ClientBase<ePortafolioMVC.IISA_WSP.IWSGeneral>, ePortafolioMVC.IISA_WSP.IWSGeneral {
        
        public WSGeneralClient() {
        }
        
        public WSGeneralClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSGeneralClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSGeneralClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSGeneralClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetNombreAlumno(string Codigo) {
            return base.Channel.GetNombreAlumno(Codigo);
        }
    }
}
